---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.1
    app.quarkus.io/commit-id: 4111eb790a42a437c9771363917a6f13dc4bda01
    app.quarkus.io/vcs-uri: https://github.com/utopios/cloud_native_juin_25.git
    app.quarkus.io/build-timestamp: 2024-06-06 - 12:27:55 +0000
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.1
    app.quarkus.io/commit-id: 4111eb790a42a437c9771363917a6f13dc4bda01
    app.quarkus.io/vcs-uri: https://github.com/utopios/cloud_native_juin_25.git
    app.quarkus.io/build-timestamp: 2024-06-06 - 12:27:55 +0000
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/name: demo
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.11.1
        app.quarkus.io/commit-id: 4111eb790a42a437c9771363917a6f13dc4bda01
        app.quarkus.io/vcs-uri: https://github.com/utopios/cloud_native_juin_25.git
        app.quarkus.io/build-timestamp: 2024-06-06 - 12:27:55 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: demo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: demo-quarkus:latest
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
